package uk.gov.hmcts.juror.api.moj.service;

/**
 * Pool Numbers are generated by the system based on a provided formula (see implementation class(es) for more details
 * on specific formula implementation(s)).
 */
public interface GenerateCoronerPoolNumberService {

    String generateCoronerPoolNumber();

}
