DELETE FROM juror_mod.voters;

-- updated some voters to have FLAGS set to X to indicate they cannot be chosen
INSERT INTO juror_mod.voters (LOC_CODE,PART_NO,REGISTER_LETT,POLL_NUMBER,NEW_MARKER,TITLE,LNAME,FNAME,DOB,FLAGS,ADDRESS,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,ZIP,DATE_SELECTED1,DATE_SELECTED2,DATE_SELECTED3,REC_NUM,PERM_DISQUAL,SOURCE_ID)
VALUES ('415','641500001','1','1',NULL,NULL,'LNAMEONE','FNAMEONE',NULL,NULL,'1 STREET NAME','ANYTOWN',NULL,NULL,NULL,NULL,'CH1 2AN',NULL,NULL,NULL,1,NULL,NULL);
INSERT INTO juror_mod.voters (LOC_CODE,PART_NO,REGISTER_LETT,POLL_NUMBER,NEW_MARKER,TITLE,LNAME,FNAME,DOB,FLAGS,ADDRESS,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,ZIP,DATE_SELECTED1,DATE_SELECTED2,DATE_SELECTED3,REC_NUM,PERM_DISQUAL,SOURCE_ID)
VALUES ('415','641500002','2','2',NULL,NULL,'LNAMETWO','FNAMETWO',NULL,NULL,'2 STREET NAME','ANYTOWN',NULL,NULL,NULL,NULL,'CH1 2AN',NULL,NULL,NULL,2,NULL,NULL);
INSERT INTO juror_mod.voters (LOC_CODE,PART_NO,REGISTER_LETT,POLL_NUMBER,NEW_MARKER,TITLE,LNAME,FNAME,DOB,FLAGS,ADDRESS,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,ZIP,DATE_SELECTED1,DATE_SELECTED2,DATE_SELECTED3,REC_NUM,PERM_DISQUAL,SOURCE_ID)
VALUES ('415','641500003','3','3',NULL,NULL,'LNAMETHREE','FNAMETHREE',NULL,NULL,'3 STREET NAME','ANYTOWN',NULL,NULL,NULL,NULL,'CH1 2AN',NULL,NULL,NULL,3,NULL,NULL);
INSERT INTO juror_mod.voters (LOC_CODE,PART_NO,REGISTER_LETT,POLL_NUMBER,NEW_MARKER,TITLE,LNAME,FNAME,DOB,FLAGS,ADDRESS,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,ZIP,DATE_SELECTED1,DATE_SELECTED2,DATE_SELECTED3,REC_NUM,PERM_DISQUAL,SOURCE_ID)
VALUES ('415','641500004','4','4',NULL,NULL,'LNAMEFOUR','FNAMEFOUR',NULL,NULL,'4 STREET NAME','ANYTOWN',NULL,NULL,NULL,NULL,'CH1 2AN',NULL,NULL,NULL,4,NULL,NULL);
INSERT INTO juror_mod.voters (LOC_CODE,PART_NO,REGISTER_LETT,POLL_NUMBER,NEW_MARKER,TITLE,LNAME,FNAME,DOB,FLAGS,ADDRESS,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,ZIP,DATE_SELECTED1,DATE_SELECTED2,DATE_SELECTED3,REC_NUM,PERM_DISQUAL,SOURCE_ID)
VALUES ('415','641500005','5','5',NULL,NULL,'LNAMEFIVE','FNAMEFIVE',NULL,NULL,'5 STREET NAME','ANYTOWN',NULL,NULL,NULL,NULL,'CH1 2AN',TIMESTAMP '2022-09-04 00:00:00.000000',NULL,NULL,5,NULL,NULL);
INSERT INTO juror_mod.voters (LOC_CODE,PART_NO,REGISTER_LETT,POLL_NUMBER,NEW_MARKER,TITLE,LNAME,FNAME,DOB,FLAGS,ADDRESS,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,ZIP,DATE_SELECTED1,DATE_SELECTED2,DATE_SELECTED3,REC_NUM,PERM_DISQUAL,SOURCE_ID)
VALUES ('415','641500006','6','6',NULL,NULL,'LNAMESIX','FNAMESIX',NULL,'X','6 STREET NAME','ANYTOWN',NULL,NULL,NULL,NULL,'CH1 2AN',NULL,NULL,NULL,6,NULL,NULL);
INSERT INTO juror_mod.voters (LOC_CODE,PART_NO,REGISTER_LETT,POLL_NUMBER,NEW_MARKER,TITLE,LNAME,FNAME,DOB,FLAGS,ADDRESS,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,ZIP,DATE_SELECTED1,DATE_SELECTED2,DATE_SELECTED3,REC_NUM,PERM_DISQUAL,SOURCE_ID)
VALUES ('415','641500007','7','7',NULL,NULL,'LNAMESEVEN','FNAMESEVEN',NULL,NULL,'7 STREET NAME','ANYTOWN',NULL,NULL,NULL,NULL,'CH1 2AN',NULL,NULL,NULL,7,NULL,NULL);
INSERT INTO juror_mod.voters (LOC_CODE,PART_NO,REGISTER_LETT,POLL_NUMBER,NEW_MARKER,TITLE,LNAME,FNAME,DOB,FLAGS,ADDRESS,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,ZIP,DATE_SELECTED1,DATE_SELECTED2,DATE_SELECTED3,REC_NUM,PERM_DISQUAL,SOURCE_ID)
VALUES ('415','641500008','8','8',NULL,NULL,'LNAMEEIGHT','FNAMEEIGHT',NULL,NULL,'8 STREET NAME','ANYTOWN',NULL,NULL,NULL,NULL,'CH1 2AN',NULL,NULL,NULL,8,NULL,NULL);
INSERT INTO juror_mod.voters (LOC_CODE,PART_NO,REGISTER_LETT,POLL_NUMBER,NEW_MARKER,TITLE,LNAME,FNAME,DOB,FLAGS,ADDRESS,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,ZIP,DATE_SELECTED1,DATE_SELECTED2,DATE_SELECTED3,REC_NUM,PERM_DISQUAL,SOURCE_ID)
VALUES ('415','641500009','9','9',NULL,NULL,'LNAMENINE','FNAMENINE',NULL,NULL,'9 STREET NAME','ANYTOWN',NULL,NULL,NULL,NULL,'CH2 2AB',TIMESTAMP '2022-04-17 00:00:00.000000',NULL,NULL,9,NULL,NULL);
INSERT INTO juror_mod.voters (LOC_CODE,PART_NO,REGISTER_LETT,POLL_NUMBER,NEW_MARKER,TITLE,LNAME,FNAME,DOB,FLAGS,ADDRESS,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,ZIP,DATE_SELECTED1,DATE_SELECTED2,DATE_SELECTED3,REC_NUM,PERM_DISQUAL,SOURCE_ID)
VALUES ('415','641500010','10','10',NULL,NULL,'LNAMEONEZERO','FNAMEONEZERO',NULL,'X','10 STREET NAME','ANYTOWN',NULL,NULL,NULL,NULL,'CH2 2AB',NULL,NULL,NULL,10,NULL,NULL);
INSERT INTO juror_mod.voters (LOC_CODE,PART_NO,REGISTER_LETT,POLL_NUMBER,NEW_MARKER,TITLE,LNAME,FNAME,DOB,FLAGS,ADDRESS,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,ZIP,DATE_SELECTED1,DATE_SELECTED2,DATE_SELECTED3,REC_NUM,PERM_DISQUAL,SOURCE_ID)
VALUES ('415','641500011','11','11',NULL,NULL,'LNAMEONEZERO','FNAMEONEZERO',NULL,NULL,'11 STREET NAME','ANYTOWN',NULL,NULL,NULL,NULL,'CH2 2AB',NULL,NULL,NULL,11,NULL,NULL);
INSERT INTO juror_mod.voters (LOC_CODE,PART_NO,REGISTER_LETT,POLL_NUMBER,NEW_MARKER,TITLE,LNAME,FNAME,DOB,FLAGS,ADDRESS,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,ZIP,DATE_SELECTED1,DATE_SELECTED2,DATE_SELECTED3,REC_NUM,PERM_DISQUAL,SOURCE_ID)
VALUES ('415','641500012','12','12',NULL,NULL,'LNAMESEVEN','FNAMESEVEN',NULL,NULL,'12 STREET NAME','ANYTOWN',NULL,NULL,NULL,NULL,'CH1 2AN',NULL,NULL,NULL,12,NULL,NULL);
