
INSERT INTO JUROR_DIGITAL.STAFF (LOGIN, NAME, RANK, ACTIVE, TEAM_ID, VERSION) VALUES ('ksalazar', 'Kris Salazar', 1, 1, 3, 1);

INSERT INTO JUROR_DIGITAL.expenses_rates values ('TRAVEL_BICYCLE_PER_MILE', 0.096);

INSERT INTO JUROR_DIGITAL.expenses_rates values ('TRAVEL_MOTORCYCLE_PER_MILE', 0.314);

INSERT INTO JUROR_DIGITAL.expenses_rates values ('TRAVEL_CAR_PER_MILE', 0.314);

INSERT INTO JUROR_DIGITAL.expenses_rates values ('SUBSISTENCE_PER_DAY', 5.71);

INSERT INTO JUROR_DIGITAL.expenses_rates values ('EARNING_TEN_DAYS_FOUR_HRS_MORE', 64.95);

INSERT INTO JUROR_DIGITAL.expenses_rates values ('EARNING_TEN_DAYS_FOUR_HRS_LESS', 32.47);
