DELETE FROM juror_mod.pool_comments;
DELETE FROM juror_mod.juror_pool;
DELETE FROM juror_mod.pool;

INSERT INTO JUROR_MOD.POOL
(OWNER, POOL_NO, LOC_CODE, NEW_REQUEST, RETURN_DATE, POOL_TYPE, TOTAL_NO_REQUIRED, NO_REQUESTED, ADDITIONAL_SUMMONS)
VALUES('400', '415221001', '415', 'T', '2022-10-03', 'CRO', 10, 9, NULL);
