-- juror
INSERT INTO JUROR.POOL (PART_NO, FNAME, LNAME, H_EMAIL, TITLE, DOB, ADDRESS, ADDRESS2, ADDRESS3, ADDRESS4, ZIP, H_PHONE, W_PHONE, IS_ACTIVE, OWNER, LOC_CODE, M_PHONE, RESPONDED, POLL_NUMBER, POOL_NO, ON_CALL, COMPLETION_FLAG, READ_ONLY, CONTACT_PREFERENCE, REG_SPC, RET_DATE, STATUS, NEXT_DATE) VALUES (644892530, 'JANE', 'CASTILLO', 'jcastillo0@ed.gov', 'DR', TO_DATE('1984-07-24 16:04:09', 'YYYY-MM-DD HH24:MI:SS'), '4 Knutson Trail', 'Scotland', 'Aberdeen', 'United Kingdom', 'AB3 9RY', '07032096993', '01095495625', 'Y', '400', '448', '01455252390', 'N', 21112, 555, 'N', 'N', 'N', 0, 'N', CURRENT_DATE, 1, (SELECT CURRENT_DATE+30));

-- enable court
INSERT INTO JUROR_DIGITAL.COURT_WHITELIST (LOC_CODE) VALUES ('448');

-- create response
INSERT INTO JUROR_DIGITAL.JUROR_RESPONSE (JUROR_NUMBER,DATE_RECEIVED,TITLE,FIRST_NAME,LAST_NAME,ADDRESS,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,ZIP,PROCESSING_STATUS,DATE_OF_BIRTH,PHONE_NUMBER,ALT_PHONE_NUMBER,EMAIL,THIRDPARTY_REASON,RESIDENCY,RESIDENCY_DETAIL,MENTAL_HEALTH_ACT,MENTAL_HEALTH_ACT_DETAILS,BAIL,BAIL_DETAILS,CONVICTIONS,CONVICTIONS_DETAILS,DEFERRAL_REASON,DEFERRAL_DATE,SPECIAL_NEEDS_ARRANGEMENTS,EXCUSAL_REASON, VERSION, JUROR_PHONE_DETAILS, JUROR_EMAIL_DETAILS) VALUES (644892530,(SELECT CURRENT_DATE - interval '0' minute),'MS','JUNE','CASSILLO','4 Knutson Trail','Scotland','Aberdeen','United Kingdom',null,null,'AB3 9RY','TODO',null,null,null,null,null,'0',null,'0',null,'0',null,'0',null,null,null,null,null,555,'Y', 'Y');

-- team member with login enabled

INSERT INTO juror_mod.users (owner, username, name, level, active,password,team_id)
VALUES ('400','testlogin','Test Login',1,true,'5baa61e4c9b93f3f',1);
--
