-- juror 644892530
INSERT INTO JUROR.POOL (PART_NO, FNAME, LNAME, H_EMAIL, TITLE, DOB, ADDRESS, ADDRESS2, ADDRESS3, ADDRESS4, ZIP, H_PHONE, W_PHONE, IS_ACTIVE, OWNER, LOC_CODE, M_PHONE, RESPONDED, POLL_NUMBER, POOL_NO, ON_CALL, COMPLETION_FLAG, READ_ONLY, CONTACT_PREFERENCE, REG_SPC, RET_DATE, NEXT_DATE, STATUS) VALUES ('644892530', 'JANE', 'CASTILLO', 'jcastillo0@ed.gov', 'DR', TO_DATE('1984-07-24 16:04:09', 'YYYY-MM-DD HH24:MI:SS'), '4 Knutson Trail', 'Scotland', 'Aberdeen', 'United Kingdom', 'AB3 9RY', '07032096993', '01095495625', 'Y', '400', '448', '01455252390', 'N', 21112, 555, 'N', 'N', 'N', 0, 'N' , CURRENT_DATE, CURRENT_DATE + 35, 1);

-- enable court
INSERT INTO JUROR_DIGITAL.COURT_WHITELIST (LOC_CODE) VALUES ('448');

-- response 644892530 (LAST_NAME changed)
INSERT INTO JUROR_DIGITAL.JUROR_RESPONSE (JUROR_NUMBER, DATE_RECEIVED, TITLE, FIRST_NAME, LAST_NAME, ADDRESS, ADDRESS2, ADDRESS3, ADDRESS4, ZIP, PROCESSING_STATUS, DATE_OF_BIRTH, PHONE_NUMBER, ALT_PHONE_NUMBER, EMAIL, RESIDENCY, RESIDENCY_DETAIL, MENTAL_HEALTH_ACT, MENTAL_HEALTH_ACT_DETAILS, BAIL, BAIL_DETAILS, CONVICTIONS, CONVICTIONS_DETAILS, DEFERRAL_REASON, DEFERRAL_DATE, SPECIAL_NEEDS_ARRANGEMENTS, EXCUSAL_REASON, PROCESSING_COMPLETE, VERSION) VALUES ('644892530' , CURRENT_DATE, 'DR', 'JANE', 'DOE', '4 Knutson Trail', 'Scotland', 'Aberdeen', 'United Kingdom', 'AB3 9RY', 'TODO', TO_DATE('1984-07-24 16:04:09', 'YYYY-MM-DD HH24:MI:SS'), '07032096993', '01095495625', 'jcastillo0@ed.gov', 'Y', NULL, 'N', NULL, 'N', NULL, 'N', NULL, 'I am working in another country', 'Will return to the UK in 4 weeks time', NULL, NULL, 'N', 2);
INSERT INTO JUROR_DIGITAL.JUROR_RESPONSE_SPECIAL_NEEDS (ID, JUROR_NUMBER, SPEC_NEED, SPEC_NEED_DETAIL) VALUES (1, '644892530', 'V', 'Photosensitive epilepsy');

-- redundant amend entry 644892530
INSERT INTO JUROR.PART_AMENDMENTS(OWNER, PART_NO, EDIT_DATE, EDIT_USERID, TITLE, FNAME, LNAME, DOB, ADDRESS, ZIP) VALUES('400', '644892530' , CURRENT_DATE, 'TESTSQL', ' ', null, null, TO_DATE('1901-01-01 00:00:01', 'YYYY-MM-DD HH24:MI:SS'), null, null);

-- redundant history entry 644892530
INSERT INTO JUROR.PART_HIST(OWNER, PART_NO, DATE_PART, HISTORY_CODE, USER_ID, OTHER_INFORMATION, POOL_NO, LAST_UPDATE) VALUES('400', '644892530' , CURRENT_DATE, 'RSUM', 'TESTSQL', 'Summoned', '' , CURRENT_DATE);

-- staff doing the edit
INSERT INTO juror_mod.users (owner, username, name, level, active,password)
VALUES ('448','STAFF1','Staff One',1,true,'5baa61e4c9b93f3f');