INSERT INTO juror_mod.juror_response (
    juror_number,
    date_received,
    title,
    first_name,
    last_name,
    address_line_1,
    address_line_2,
    address_line_3,
    address_line_4,
    address_line_5,
    postcode,
    processing_status,
    date_of_birth,
    phone_number,
    alt_phone_number,
    email,
    residency,
    residency_detail,
    mental_health_act,
    mental_health_act_details,
    bail,
    bail_details,
    convictions,
    convictions_details,
    deferral_reason,
    deferral_date,
    reasonable_adjustments_arrangements,
    excusal_reason,
    processing_complete,
    version,
    thirdparty_fname,
    thirdparty_lname,
    relationship,
    main_phone,
    other_phone,
    email_address,
    thirdparty_reason,
    thirdparty_other_reason,
    juror_phone_details,
    juror_email_details,
    staff_login,
    staff_assignment_date,
    urgent,
    completed_at,
    welsh,
    reply_type
) VALUES (
    '555555571',
    TIMESTAMP '2023-03-08 00:00:00.000000',
    'Mr',
    'Juror571',
    'Juror571Surname',
    'Address Line 1',
    'Address Line 2',
    'Address Line 3',
    'CARDIFF',
    'Some County',
    'CH1 2AN',
    'TODO',
    TIMESTAMP '1998-03-08 00:00:00.000000',
    NULL,
    NULL,
    NULL,
    'Y',
    NULL,
    'N',
    NULL,
    'N',
    NULL,
    'N',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'N',
    0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'N',
    NULL,
    'N',
    'Paper'
);
