DELETE FROM juror_mod.courtroom;
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('442', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('442', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('442', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('442', 'Court', 'COURT ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('442', 'CT 2', 'COURT 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('442', 'CT 3', 'COURT 3');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('442', 'CT 4', 'COURT 4');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('442', 'CT 5', 'COURT 5');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('442', 'CT 6', 'COURT 6');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('442', 'FLOAT', 'FLOATING COURT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('442', 'BACK', 'BACKER');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('417', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('417', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('417', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('417', 'Court', 'COURT ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('417', 'CT1', 'COURT 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('417', 'CT2', 'COURT 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('417', 'CT3', 'COURT 3');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('417', 'FLOAT', 'FLOATING TRIAL COURT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'Court', 'COURT ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'CT1', 'COURT 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'CT2', 'COURT 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'CT3', 'COURT 3');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'CT4', 'COURT 4');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'CT5', 'COURT 5');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'CT6', 'COURT 6');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'CT7', 'COURT 7');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'CT8', 'COURT 8 ');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'CT9', 'COURT 9');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'CT10', 'COURT 10');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'FLOAT', 'FLOATING COURT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'CT11', 'COURT 11');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'CT12', 'COURT 12');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('440', 'CT13', 'COURT 13');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('415', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('415', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('415', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('415', 'CT 1', 'COURT 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('415', 'CT 2', 'COURT 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('415', 'CT 3', 'COURT 3');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('415', 'CT 4', 'COURT 4');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('415', 'FLOAT', 'FLOATING COURT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'Court', 'COURT ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'CT1', 'COURT 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'CT2', 'COURT 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'CT3', 'COURT 3');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'CT4', 'COURT 4');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'CT 5', 'COURT 5');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'CT6', 'COURT 6');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'CT7', 'COURT 7');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'CT8', 'COURT 8');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'CT9', 'COURT 9');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'CT10', 'COURT 10');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'FLOAT', 'FLOATING COURT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'MOOT1', 'MOOT HALL 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('439', 'MOOT2', 'MOOT HALL 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('456', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('456', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('456', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('456', 'CT1', 'COURT 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('456', 'CT2', 'COURT 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('456', 'CT3', 'COURT 3');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('456', 'CT4', 'COURT 4');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('456', 'CT5', 'COURT 5');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('456', 'FLOAT', 'FLOAT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('463', 'Asmbly', 'JURY ASSEMBLY ');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('463', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('463', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('463', 'CT 1', 'COURT 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('463', 'CT 2', 'COURT 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('463', 'CT 3', 'COURT 3');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('463', 'FLOA', 'FLOATER');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'Court', 'COURT ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'COURT1', 'COURT 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'COURT2', 'COURT 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'COURT3', 'COURT 3');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'COURT4', 'COURT 4');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'COURT5', 'COURT 5');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'COURT6', 'COURT 6');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'COURT7', 'COURT 7');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'COURT8', 'COURT 8');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'COURT9', 'COURT 9');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'CT 10', 'COURT 10');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'CT 11', 'COURT 11');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'CT 12', 'COURT 12');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'CT 13', 'COURT 13');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('408', 'FLOAT', 'FLOATER');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('431', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('431', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('431', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('431', 'Court', 'COURT ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('431', 'CT 1', 'COURT 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('431', 'CT 2', 'COURT 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('431', 'CT 3', 'COURT 3');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('431', 'CT 4', 'COURT 4');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('431', 'FLOAT', 'FLOATING COURT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('458', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('458', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('458', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('458', 'Court', 'COURT ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('458', 'CT1', 'COURT 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('458', 'CT2', 'COURT 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('458', 'FLOAT', 'FLOATING COURT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'Court', 'COURT ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'CT 1', 'COURT 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'CT 2', 'COURT 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'CT 3', 'COURT 3');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'CT 4', 'COURT 4');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'CT 5', 'COURT 5');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'CT 6', 'COURT 6');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'FLOAT', 'FLOATING COURT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'CT 9', 'COURT 9');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'CT 7', 'COURT 7');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('449', 'CT 8', 'COURT 8');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('411', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('411', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('411', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('411', 'Court', 'COURT ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('433', '4-4A', 'Court 4-4A');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('433', '3-3A', 'Court 3-3A');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('799', 'BT 1', 'BTON CT 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('413', 'ACT 1', 'Aldersgate House Court 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('413', 'ACT 2', 'Aldersgate House Court 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('404', 'CT 14 ', 'Court 14');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('404', 'CT 15 ', 'Court 15');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('411', 'FLOAT', 'floating trial');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('403', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('403', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('403', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('403', 'Court', 'COURT ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('403', 'CT1', 'COURT 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('403', 'CT2', 'COURT 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('403', 'CT3', 'COURT 3');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('403', 'CT4', 'COURT 4');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('403', 'CT5', 'COURT 5');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('403', 'CT6', 'COURT 6');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('403', 'FLOAT', 'FLOATING CASE');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('443', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('443', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('443', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('443', 'CT 1', 'COURT ONE');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('443', 'CT 2', 'COURT TWO');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('443', 'CT 3', 'COURT THREE');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('443', 'CT 4', 'COURT FOUR');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('443', 'CT 5', 'COURT FIVE');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('443', 'CT 6', 'COURT SIX');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('443', 'K L', 'KINGS LYNN');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('443', 'FL', 'FIRST AVAILABLE COURT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('407', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('407', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('407', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('407', 'Court', 'COURT ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('407', 'COURT', 'COURT 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('478', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('478', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('478', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('478', 'Court', 'COURT ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('406', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('406', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('406', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('406', 'COURT1', 'Court 1');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('406', 'COURT2', 'Court 2');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('406', 'COURT3', 'Court 3');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('406', 'COURT4', 'Court 4');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('406', 'COURT5', 'Court 5');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('406', 'COURT6', 'Court 6');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('406', 'COURT7', 'Court 7');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('406', 'FLOAT', 'FLOATING COURTROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'Navail', 'Not Available');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'ChkOut', 'PARTICIPANT CHECKED OUT');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'Court', 'COURT ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'CT 1.', 'COURT 1.');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'CT 2.', 'COURT 2.');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'CT 3.', 'COURT 3.');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'CT 4.', 'COURT 4.');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'CT 5.', 'COURT 5.');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'CT 6.', 'COURT 6.');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'CT 7.', 'COURT 7.');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'CT 8.', 'COURT 8.');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'FLOAT', 'FLOATING TRIAL');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'CT 9', 'COURT 9');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'CT 10', 'COURT 10');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'CT 11', 'COURT 11');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'CT 12', 'COURT 12');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('475', 'CT 13', 'COURT 13');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('457', 'Asmbly', 'JURY ASSEMBLY ROOM');
INSERT INTO juror_mod.courtroom (loc_code, room_number, description) VALUES('457', 'Navail', 'Not Available');