-- juror_mod.low_level_financial_audit_details_including_approved_amounts source

CREATE OR REPLACE VIEW juror_mod.low_level_financial_audit_details_including_approved_amounts
AS SELECT llfad2.public_transport_total_approved,
          llfad2.hired_vehicle_total_approved,
          llfad2.motorcycle_total_approved,
          llfad2.car_total_approved,
          llfad2.pedal_cycle_total_approved,
          llfad2.parking_total_approved,
          llfad2.loss_of_earnings_approved,
          llfad2.childcare_total_approved,
          llfad2.misc_total_approved,
          llfad2.subsistence_approved,
          llfad2.smart_card_approved,
          llfad2.id,
          llfad2.juror_revision,
          llfad2.court_location_revision,
          llfad2.type,
          llfad2.created_by,
          llfad2.created_on,
          llfad2.juror_number,
          llfad2.loc_code,
          llfad2.created_on_date,
          llfad2.last_approved_faudit,
          llfad2.attendance_date,
          llfad2.pool_number,
          llfad2.trial_number,
          llfad2.appearance_stage,
          llfad2.attendance_type,
          llfad2.is_draft_expense,
          llfad2.pay_cash,
          llfad2.f_audit,
          llfad2.attendance_audit_number,
          llfad2.public_transport_total_due,
          llfad2.hired_vehicle_total_due,
          llfad2.motorcycle_total_due,
          llfad2.car_total_due,
          llfad2.pedal_cycle_total_due,
          llfad2.parking_total_due,
          llfad2.loss_of_earnings_due,
          llfad2.childcare_total_due,
          llfad2.misc_total_due,
          llfad2.subsistence_due,
          llfad2.smart_card_due,
          llfad2.public_transport_total_paid,
          llfad2.hired_vehicle_total_paid,
          llfad2.motorcycle_total_paid,
          llfad2.car_total_paid,
          llfad2.pedal_cycle_total_paid,
          llfad2.parking_total_paid,
          llfad2.loss_of_earnings_paid,
          llfad2.childcare_total_paid,
          llfad2.misc_total_paid,
          llfad2.subsistence_paid,
          llfad2.smart_card_paid,
          llfad2.total_travel_due,
          llfad2.total_travel_paid,
          llfad2.total_financial_loss_due,
          llfad2.total_financial_loss_paid,
          llfad2.total_subsistence_due,
          llfad2.total_subsistence_paid,
          llfad2.total_smart_card_due,
          llfad2.total_smart_card_paid,
          llfad2.total_travel_outstanding,
          llfad2.total_financial_loss_outstanding,
          llfad2.total_subsistence_outstanding,
          llfad2.total_smartcard_outstanding,
          llfad2.total_due,
          llfad2.total_paid,
          llfad2.total_outstanding,
          llfad2.public_transport_total_approved + llfad2.hired_vehicle_total_approved + llfad2.motorcycle_total_approved + llfad2.car_total_approved + llfad2.pedal_cycle_total_approved + llfad2.parking_total_approved + llfad2.loss_of_earnings_approved + llfad2.childcare_total_approved + llfad2.misc_total_approved + llfad2.subsistence_approved + llfad2.smart_card_approved AS total_approved,
          llfad2.public_transport_total_approved + llfad2.hired_vehicle_total_approved + llfad2.motorcycle_total_approved + llfad2.car_total_approved + llfad2.pedal_cycle_total_approved + llfad2.parking_total_approved AS total_travel_approved,
          llfad2.loss_of_earnings_approved + llfad2.childcare_total_approved + llfad2.misc_total_approved AS total_financial_loss_approved,
          llfad2.subsistence_approved AS total_subsistence_approved,
          llfad2.smart_card_approved AS total_smartcard_approved
   FROM ( SELECT llfad.public_transport_total_paid - COALESCE(lastapprovedllfad.public_transport_total_paid, 0::numeric) AS public_transport_total_approved,
                 llfad.hired_vehicle_total_paid - COALESCE(lastapprovedllfad.hired_vehicle_total_paid, 0::numeric) AS hired_vehicle_total_approved,
                 llfad.motorcycle_total_paid - COALESCE(lastapprovedllfad.motorcycle_total_paid, 0::numeric) AS motorcycle_total_approved,
                 llfad.car_total_paid - COALESCE(lastapprovedllfad.car_total_paid, 0::numeric) AS car_total_approved,
                 llfad.pedal_cycle_total_paid - COALESCE(lastapprovedllfad.pedal_cycle_total_paid, 0::numeric) AS pedal_cycle_total_approved,
                 llfad.parking_total_paid - COALESCE(lastapprovedllfad.parking_total_paid, 0::numeric) AS parking_total_approved,
                 llfad.loss_of_earnings_paid - COALESCE(lastapprovedllfad.loss_of_earnings_paid, 0::numeric) AS loss_of_earnings_approved,
                 llfad.childcare_total_paid - COALESCE(lastapprovedllfad.childcare_total_paid, 0::numeric) AS childcare_total_approved,
                 llfad.misc_total_paid - COALESCE(lastapprovedllfad.misc_total_paid, 0::numeric) AS misc_total_approved,
                 llfad.subsistence_paid - COALESCE(lastapprovedllfad.subsistence_paid, 0::numeric) AS subsistence_approved,
                 CASE
                     WHEN llfad.type::text = ANY (ARRAY['REAPPROVED_CASH'::character varying, 'REAPPROVED_BACS'::character varying]::text[])
                     THEN COALESCE(lastapprovedllfad.smart_card_paid, 0::numeric) - llfad.smart_card_paid
                     ELSE -(llfad.smart_card_paid - COALESCE(lastapprovedllfad.smart_card_paid, 0::numeric))
                     END AS smart_card_approved,
                 llfad.id,
                 llfad.juror_revision,
                 llfad.court_location_revision,
                 llfad.type,
                 llfad.created_by,
                 llfad.created_on,
                 llfad.juror_number,
                 llfad.loc_code,
                 llfad.created_on_date,
                 llfad.last_approved_faudit,
                 llfad.attendance_date,
                 llfad.pool_number,
                 llfad.trial_number,
                 llfad.appearance_stage,
                 llfad.attendance_type,
                 llfad.is_draft_expense,
                 llfad.pay_cash,
                 llfad.f_audit,
                 llfad.attendance_audit_number,
                 llfad.public_transport_total_due,
                 llfad.hired_vehicle_total_due,
                 llfad.motorcycle_total_due,
                 llfad.car_total_due,
                 llfad.pedal_cycle_total_due,
                 llfad.parking_total_due,
                 llfad.loss_of_earnings_due,
                 llfad.childcare_total_due,
                 llfad.misc_total_due,
                 llfad.subsistence_due,
                 llfad.smart_card_due,
                 llfad.public_transport_total_paid,
                 llfad.hired_vehicle_total_paid,
                 llfad.motorcycle_total_paid,
                 llfad.car_total_paid,
                 llfad.pedal_cycle_total_paid,
                 llfad.parking_total_paid,
                 llfad.loss_of_earnings_paid,
                 llfad.childcare_total_paid,
                 llfad.misc_total_paid,
                 llfad.subsistence_paid,
                 llfad.smart_card_paid,
                 llfad.total_travel_due,
                 llfad.total_travel_paid,
                 llfad.total_financial_loss_due,
                 llfad.total_financial_loss_paid,
                 llfad.total_subsistence_due,
                 llfad.total_subsistence_paid,
                 llfad.total_smart_card_due,
                 llfad.total_smart_card_paid,
                 llfad.total_travel_outstanding,
                 llfad.total_financial_loss_outstanding,
                 llfad.total_subsistence_outstanding,
                 llfad.total_smartcard_outstanding,
                 llfad.total_due,
                 llfad.total_paid,
                 llfad.total_outstanding
          FROM juror_mod.low_level_financial_audit_details llfad
                   LEFT JOIN juror_mod.low_level_financial_audit_details lastapprovedllfad ON lastapprovedllfad.id = llfad.last_approved_faudit AND lastapprovedllfad.loc_code::text = llfad.loc_code::text AND lastapprovedllfad.attendance_date = llfad.attendance_date AND (llfad.type::text = ANY (ARRAY['REAPPROVED_BACS'::character varying, 'REAPPROVED_CASH'::character varying]::text[]))) llfad2;