CREATE TABLE juror_mod.juror
(
    juror_number        varchar(9)  NOT NULL,
    poll_number         varchar(5) NULL,
    title               varchar(10) NULL,
    last_name           varchar(20) NOT NULL,
    first_name          varchar(20) NOT NULL,
    dob                 timestamp(0) NULL,
    address             varchar(35) NOT NULL,
    address2            varchar(35) NULL,
    address3            varchar(35) NULL,
    address4            varchar(35) NULL,
    address5            varchar(35) NULL,
    address6            varchar(35) NULL,
    zip                 varchar(10) NULL,
    h_phone             varchar(15) NULL,
    w_phone             varchar(15) NULL,
    w_ph_local          varchar(4) NULL,
    responded           bool        NOT NULL,
    date_excused        timestamp(0) NULL,
    excusal_code        varchar(1) NULL,
    acc_exc             varchar(1) NULL,
    date_disq           timestamp(0) NULL,
    disq_code           varchar(1) NULL,
    user_edtq           varchar(20) NULL,
    notes               varchar(2000) NULL,
    no_def_pos          integer NULL,
    perm_disqual        bool NULL,
    reasonable_adj_code varchar(1) NULL,
    reasonable_adj_msg  varchar(60) NULL,
    smart_card          varchar(20) NULL,
    completion_flag     bool NULL,
    completion_date     timestamp(0) NULL,
    sort_code           varchar(6) NULL,
    bank_acct_name      varchar(18) NULL,
    bank_acct_no        varchar(8) NULL,
    bldg_soc_roll_no    varchar(18) NULL,
    welsh               bool NULL,

    police_check        varchar(50) NULL DEFAULT 'NOT_CHECKED',
    last_update         timestamp(0) NULL,
    summons_file        varchar(20) NULL,
    m_phone             varchar(15) NULL,
    h_email             varchar(254) NULL,
    contact_preference  integer NULL DEFAULT 0,
    notifications       integer NULL DEFAULT 0,
    date_created        timestamp NULL,
    optic_reference     varchar(8) NULL,
    pending_title       varchar(10) NULL,
    pending_first_name  varchar(20) NULL,
    pending_last_name   varchar(20) NULL,
    CONSTRAINT juror_pk PRIMARY KEY (juror_number),
    CONSTRAINT police_check_val CHECK (police_check
        IN (
        'INSUFFICIENT_INFORMATION',
        'NOT_CHECKED',
        'IN_PROGRESS',
        'ELIGIBLE',
        'INELIGIBLE',
        'ERROR_RETRY_NAME_HAS_NUMERICS',
        'ERROR_RETRY_CONNECTION_ERROR',
        'ERROR_RETRY_OTHER_ERROR_CODE',
        'ERROR_RETRY_NO_ERROR_REASON',
        'ERROR_RETRY_UNEXPECTED_EXCEPTION',
        'UNCHECKED_MAX_RETRIES_EXCEEDED'
        ))
);
CREATE INDEX i_zip_1 ON juror_mod.juror USING btree (zip);
CREATE INDEX last_name_1 ON juror_mod.juror USING btree (last_name);