drop view if exists juror_mod.mod_juror_detail ;

CREATE OR REPLACE VIEW juror_mod.mod_juror_detail
AS WITH juror_details_cte AS (
         SELECT j_1.juror_number,
            COALESCE(s.pool_no, jp.pool_number) AS pool_no,
            COALESCE(s.service_start_date, p.return_date) AS ret_date,
            COALESCE(s.loc_code, p.loc_code) AS loc_code,
            j_1.title,
            j_1.first_name,
            j_1.last_name,
            j_1.address_line_1,
            j_1.address_line_2,
            j_1.address_line_3,
            j_1.address_line_4,
            j_1.address_line_5,
            j_1.postcode,
            jp.next_date,
            jp.status,
            j_1.h_phone AS phone_number,
            j_1.m_phone AS alt_phone_number,
            j_1.dob,
            j_1.notes,
            j_1.h_email AS email,
            j_1.last_update,
            r.title AS new_title,
            r.first_name AS new_first_name,
            r.last_name AS new_last_name,
            r.address_line_1 AS new_address_1,
            r.address_line_2 AS new_address_2,
            r.address_line_3 AS new_address_3,
            r.address_line_4 AS new_address_4,
            r.address_line_5 AS new_address_5,
            r.postcode AS new_postcode,
            r.date_received,
            r.processing_status,
            r.phone_number AS new_phone_number,
            r.alt_phone_number AS new_alt_phone_number,
            r.date_of_birth AS new_dob,
            r.email AS new_email,
            r.thirdparty_fname,
            r.thirdparty_lname,
            r.thirdparty_reason,
            r.thirdparty_other_reason,
            r.main_phone,
            r.other_phone,
            r.email_address,
            r.relationship,
            r.residency,
            r.residency_detail,
            r.mental_health_act,
            r.mental_health_act_details,
            r.bail,
            r.bail_details,
            r.convictions,
            r.convictions_details,
            r.deferral_reason,
            r.deferral_date,
            r.reasonable_adjustments_arrangements,
            r.excusal_reason,
            r.processing_complete,
            r.completed_at,
            r.version,
            r.juror_email_details,
            r.juror_phone_details,
            r.staff_login,
            r.staff_assignment_date,
            r.urgent,
            r.super_urgent,
            r.welsh,
            r.reply_type,
            row_number() OVER (PARTITION BY j_1.juror_number ORDER BY p.return_date DESC) AS row_no
           FROM juror_mod.juror j_1
             LEFT JOIN juror_mod.juror_pool jp ON j_1.juror_number::text = jp.juror_number::text
             LEFT JOIN juror_mod.pool p ON jp.pool_number::text = p.pool_no::text
             LEFT JOIN juror_mod.juror_response r ON r.juror_number::text = j_1.juror_number::text
             LEFT JOIN juror_mod.summons_snapshot s ON r.juror_number::text = s.juror_number::text
          WHERE jp.is_active = true
        )
SELECT j.juror_number,
    j.pool_no,
    j.ret_date,
    c.loc_code,
    c.loc_name,
    c.loc_court_name,
    c.loc_address1,
    c.loc_address2,
    c.loc_address3,
    c.loc_address4,
    c.loc_address5,
    c.loc_address6,
    c.loc_zip,
    c.loc_attend_time,
    j.title,
    j.first_name,
    j.last_name,
    j.address_line_1 AS address,
    j.address_line_2 AS address2,
    j.address_line_3 AS address3,
    j.address_line_4 AS address4,
    j.address_line_5 AS address5,
    j.postcode AS zip,
    j.next_date,
    j.status,
    j.phone_number,
    j.alt_phone_number,
    j.dob,
    j.notes,
    j.email,
    j.last_update,
    j.new_title,
    j.new_first_name,
    j.new_last_name,
    j.new_address_1 AS new_address,
    j.new_address_2 AS new_address2,
    j.new_address_3 AS new_address3,
    j.new_address_4 AS new_address4,
    j.new_address_5 AS new_address5,
    j.new_postcode AS new_zip,
    j.date_received,
    j.processing_status,
    j.new_phone_number,
    j.new_alt_phone_number,
    j.new_dob,
    j.new_email,
    j.thirdparty_fname,
    j.thirdparty_lname,
    j.thirdparty_reason,
    j.thirdparty_other_reason,
    j.main_phone,
    j.other_phone,
    j.email_address,
    j.relationship,
    j.residency,
    j.residency_detail,
    j.mental_health_act,
    j.mental_health_act_details,
    j.bail,
    j.bail_details,
    j.convictions,
    j.convictions_details,
    j.deferral_reason,
    j.deferral_date,
    j.reasonable_adjustments_arrangements,
    j.excusal_reason,
    j.processing_complete,
    j.completed_at,
    j.version,
    j.juror_email_details,
    j.juror_phone_details,
    j.staff_login,
    j.staff_assignment_date,
    j.urgent,
    j.super_urgent,
    j.welsh,
    j.reply_type,
        CASE
            WHEN wl.loc_code IS NULL THEN false
            ELSE true
        END AS welsh_court
   FROM juror_details_cte j
     JOIN juror_mod.court_location c ON j.loc_code::text = c.loc_code::text
     LEFT JOIN juror_mod.welsh_court_location wl ON c.loc_code::text = wl.loc_code::text
  WHERE j.row_no = 1;


ALTER TABLE juror_mod.juror_pool DROP COLUMN ret_date;

ALTER TABLE juror_mod.coroner_pool_detail DROP COLUMN address6;