create or replace view juror_mod.juror_paper_response
AS SELECT jr.juror_number,
    jr.date_received,
    jr.title,
    jr.first_name,
    jr.last_name,
    jr.address_line_1,
    jr.address_line_2,
    jr.address_line_3,
    jr.address_line_4,
    jr.address_line_5,
    jr.postcode,
    jr.processing_status,
    jr.date_of_birth,
    jr.phone_number,
    jr.alt_phone_number,
    jr.email,
    jr.residency,
    jr.mental_health_act,
    jr.mental_health_capacity,
    jr.bail,
    jr.convictions,
    jr.reasonable_adjustments_arrangements,
    jr.relationship,
    jr.thirdparty_reason,
    jr.deferral AS excusal,
    jr.signed,
    jr.staff_login,
    jr.urgent,
    jr.processing_complete,
    jr.completed_at,
    jr.welsh,
	jr.thirdparty_fname,
    jr.thirdparty_lname,
    jr.main_phone,
    jr.other_phone,
    jr.email_address,
    jr.thirdparty_other_reason,
    jr.juror_phone_details,
    jr.juror_email_details
   FROM juror_mod.juror_response jr
  WHERE lower(jr.reply_type::text) = 'paper'::text;
