
alter table juror_mod.expense_rates
add column limit_financial_loss_half_day_extra_long_trial numeric(8, 5) null,
add column limit_financial_loss_full_day_extra_long_trial numeric(8, 5) null;

update juror_mod.expense_rates
set limit_financial_loss_half_day_extra_long_trial = 114.3,
    limit_financial_loss_full_day_extra_long_trial = 228.6;

-- drop some dependent views before recreating them after altering appearance.attendance_type
drop view juror_mod.low_level_financial_audit_details_including_approved_amounts;
drop view juror_mod.low_level_financial_audit_details;
drop view juror_mod.failed_to_attend;
drop view juror_mod.show_cause;

alter table juror_mod.appearance
 drop constraint attendance_type_val;

alter table juror_mod.appearance
  alter column attendance_type type varchar(40);

alter table juror_mod.appearance
 add constraint attendance_type_val check (((attendance_type)::text = ANY (ARRAY[('FULL_DAY'::character varying)::text, ('HALF_DAY'::character varying)::text, ('FULL_DAY_LONG_TRIAL'::character varying)::text, ('HALF_DAY_LONG_TRIAL'::character varying)::text, ('FULL_DAY_EXTRA_LONG_TRIAL'::character varying)::text, ('HALF_DAY_EXTRA_LONG_TRIAL'::character varying)::text, ('ABSENT'::character varying)::text, ('NON_ATTENDANCE'::character varying)::text, ('NON_ATTENDANCE_LONG_TRIAL'::character varying)::text, ('NON_ATTENDANCE_EXTRA_LONG_TRIAL'::character varying)::text])));


-- juror_mod.low_level_financial_audit_details source

CREATE OR REPLACE VIEW juror_mod.low_level_financial_audit_details
AS SELECT id,
    juror_revision,
    court_location_revision,
    type,
    created_by,
    created_on,
    juror_number,
    loc_code,
    created_on_date,
    last_approved_faudit,
    attendance_date,
    pool_number,
    trial_number,
    appearance_stage,
    attendance_type,
    is_draft_expense,
    pay_cash,
    f_audit,
    attendance_audit_number,
    public_transport_total_due,
    hired_vehicle_total_due,
    motorcycle_total_due,
    car_total_due,
    pedal_cycle_total_due,
    parking_total_due,
    loss_of_earnings_due,
    childcare_total_due,
    misc_total_due,
    subsistence_due,
    smart_card_due,
    public_transport_total_paid,
    hired_vehicle_total_paid,
    motorcycle_total_paid,
    car_total_paid,
    pedal_cycle_total_paid,
    parking_total_paid,
    loss_of_earnings_paid,
    childcare_total_paid,
    misc_total_paid,
    subsistence_paid,
    smart_card_paid,
    total_travel_due,
    total_travel_paid,
    total_financial_loss_due,
    total_financial_loss_paid,
    total_subsistence_due,
    total_subsistence_paid,
    total_smart_card_due,
    total_smart_card_paid,
    total_travel_outstanding,
    total_financial_loss_outstanding,
    total_subsistence_outstanding,
    total_smartcard_outstanding,
    total_due,
    total_paid,
    total_due - total_paid AS total_outstanding
   FROM ( SELECT a3.id,
            a3.juror_revision,
            a3.court_location_revision,
            a3.type,
            a3.created_by,
            a3.created_on,
            a3.juror_number,
            a3.loc_code,
            a3.created_on_date,
            a3.last_approved_faudit,
            a3.attendance_date,
            a3.pool_number,
            a3.trial_number,
            a3.appearance_stage,
            a3.attendance_type,
            a3.is_draft_expense,
            a3.pay_cash,
            a3.f_audit,
            a3.attendance_audit_number,
            a3.public_transport_total_due,
            a3.hired_vehicle_total_due,
            a3.motorcycle_total_due,
            a3.car_total_due,
            a3.pedal_cycle_total_due,
            a3.parking_total_due,
            a3.loss_of_earnings_due,
            a3.childcare_total_due,
            a3.misc_total_due,
            a3.subsistence_due,
            a3.smart_card_due,
            a3.public_transport_total_paid,
            a3.hired_vehicle_total_paid,
            a3.motorcycle_total_paid,
            a3.car_total_paid,
            a3.pedal_cycle_total_paid,
            a3.parking_total_paid,
            a3.loss_of_earnings_paid,
            a3.childcare_total_paid,
            a3.misc_total_paid,
            a3.subsistence_paid,
            a3.smart_card_paid,
            a3.total_travel_due,
            a3.total_travel_paid,
            a3.total_financial_loss_due,
            a3.total_financial_loss_paid,
            a3.total_subsistence_due,
            a3.total_subsistence_paid,
            a3.total_smart_card_due,
            a3.total_smart_card_paid,
            a3.total_travel_due - a3.total_travel_paid AS total_travel_outstanding,
            a3.total_financial_loss_due - a3.total_financial_loss_paid AS total_financial_loss_outstanding,
            a3.total_subsistence_due - a3.total_subsistence_paid AS total_subsistence_outstanding,
                CASE
                    WHEN (a3.total_smart_card_paid - a3.total_smart_card_due) >= 0::numeric THEN a3.total_smart_card_paid - a3.total_smart_card_due
                    ELSE a3.total_smart_card_due
                END AS total_smartcard_outstanding,
            a3.total_travel_due + a3.total_financial_loss_due + a3.total_subsistence_due - a3.total_smart_card_due AS total_due,
            a3.total_travel_paid + a3.total_financial_loss_paid + a3.total_subsistence_paid - a3.total_smart_card_paid AS total_paid
           FROM ( SELECT a2.id,
                    a2.juror_revision,
                    a2.court_location_revision,
                    a2.type,
                    a2.created_by,
                    a2.created_on,
                    a2.juror_number,
                    a2.loc_code,
                    a2.created_on_date,
                    a2.last_approved_faudit,
                    a2.attendance_date,
                    a2.pool_number,
                    a2.trial_number,
                    a2.appearance_stage,
                    a2.attendance_type,
                    a2.is_draft_expense,
                    a2.pay_cash,
                    a2.f_audit,
                    a2.attendance_audit_number,
                    a2.public_transport_total_due,
                    a2.hired_vehicle_total_due,
                    a2.motorcycle_total_due,
                    a2.car_total_due,
                    a2.pedal_cycle_total_due,
                    a2.parking_total_due,
                    a2.loss_of_earnings_due,
                    a2.childcare_total_due,
                    a2.misc_total_due,
                    a2.subsistence_due,
                    a2.smart_card_due,
                    a2.public_transport_total_paid,
                    a2.hired_vehicle_total_paid,
                    a2.motorcycle_total_paid,
                    a2.car_total_paid,
                    a2.pedal_cycle_total_paid,
                    a2.parking_total_paid,
                    a2.loss_of_earnings_paid,
                    a2.childcare_total_paid,
                    a2.misc_total_paid,
                    a2.subsistence_paid,
                    a2.smart_card_paid,
                    a2.public_transport_total_due + a2.hired_vehicle_total_due + a2.motorcycle_total_due + a2.car_total_due + a2.pedal_cycle_total_due + a2.parking_total_due AS total_travel_due,
                    a2.public_transport_total_paid + a2.hired_vehicle_total_paid + a2.motorcycle_total_paid + a2.car_total_paid + a2.pedal_cycle_total_paid + a2.parking_total_paid AS total_travel_paid,
                    a2.loss_of_earnings_due + a2.childcare_total_due + a2.misc_total_due AS total_financial_loss_due,
                    a2.loss_of_earnings_paid + a2.childcare_total_paid + a2.misc_total_paid AS total_financial_loss_paid,
                    a2.subsistence_due AS total_subsistence_due,
                    a2.subsistence_paid AS total_subsistence_paid,
                    a2.smart_card_due AS total_smart_card_due,
                    a2.smart_card_paid AS total_smart_card_paid
                   FROM ( SELECT fad.id,
                            fad.juror_revision,
                            fad.court_location_revision,
                            fad.type,
                            fad.created_by,
                            fad.created_on,
                            fad.juror_number,
                            fad.loc_code,
                            fad.created_on::timestamp without time zone::date AS created_on_date,
                            fada.last_approved_faudit,
                            aa.attendance_date,
                            aa.pool_number,
                            aa.trial_number,
                            aa.appearance_stage,
                            aa.attendance_type,
                            aa.is_draft_expense,
                            aa.pay_cash,
                            aa.f_audit,
                            aa.attendance_audit_number,
                            COALESCE(aa.public_transport_total_due, 0::numeric) AS public_transport_total_due,
                            COALESCE(aa.hired_vehicle_total_due, 0::numeric) AS hired_vehicle_total_due,
                            COALESCE(aa.motorcycle_total_due, 0::numeric) AS motorcycle_total_due,
                            COALESCE(aa.car_total_due, 0::numeric) AS car_total_due,
                            COALESCE(aa.pedal_cycle_total_due, 0::numeric) AS pedal_cycle_total_due,
                            COALESCE(aa.parking_total_due, 0::numeric) AS parking_total_due,
                            COALESCE(aa.loss_of_earnings_due, 0::numeric) AS loss_of_earnings_due,
                            COALESCE(aa.childcare_total_due, 0::numeric) AS childcare_total_due,
                            COALESCE(aa.misc_total_due, 0::numeric) AS misc_total_due,
                            COALESCE(aa.subsistence_due, 0::numeric) AS subsistence_due,
                            COALESCE(aa.smart_card_due, 0::numeric) AS smart_card_due,
                            COALESCE(aa.public_transport_total_paid, 0::numeric) AS public_transport_total_paid,
                            COALESCE(aa.hired_vehicle_total_paid, 0::numeric) AS hired_vehicle_total_paid,
                            COALESCE(aa.motorcycle_total_paid, 0::numeric) AS motorcycle_total_paid,
                            COALESCE(aa.car_total_paid, 0::numeric) AS car_total_paid,
                            COALESCE(aa.pedal_cycle_total_paid, 0::numeric) AS pedal_cycle_total_paid,
                            COALESCE(aa.parking_total_paid, 0::numeric) AS parking_total_paid,
                            COALESCE(aa.loss_of_earnings_paid, 0::numeric) AS loss_of_earnings_paid,
                            COALESCE(aa.childcare_total_paid, 0::numeric) AS childcare_total_paid,
                            COALESCE(aa.misc_total_paid, 0::numeric) AS misc_total_paid,
                            COALESCE(aa.subsistence_paid, 0::numeric) AS subsistence_paid,
                            COALESCE(aa.smart_card_paid, 0::numeric) AS smart_card_paid
                           FROM juror_mod.financial_audit_details fad
                             JOIN juror_mod.financial_audit_details_appearances fada ON fada.financial_audit_id = fad.id AND fada.loc_code::text = fad.loc_code::text
                             JOIN juror_mod.appearance_audit aa ON aa.loc_code::text = fada.loc_code::text AND aa.attendance_date = fada.attendance_date AND aa.juror_number::text = fad.juror_number::text AND aa.version = fada.appearance_version) a2) a3) a4;

-- juror_mod.low_level_financial_audit_details_including_approved_amounts source

CREATE OR REPLACE VIEW juror_mod.low_level_financial_audit_details_including_approved_amounts
AS SELECT public_transport_total_approved,
    hired_vehicle_total_approved,
    motorcycle_total_approved,
    car_total_approved,
    pedal_cycle_total_approved,
    parking_total_approved,
    loss_of_earnings_approved,
    childcare_total_approved,
    misc_total_approved,
    subsistence_approved,
    smart_card_approved,
    id,
    juror_revision,
    court_location_revision,
    type,
    created_by,
    created_on,
    juror_number,
    loc_code,
    created_on_date,
    last_approved_faudit,
    attendance_date,
    pool_number,
    trial_number,
    appearance_stage,
    attendance_type,
    is_draft_expense,
    pay_cash,
    f_audit,
    attendance_audit_number,
    public_transport_total_due,
    hired_vehicle_total_due,
    motorcycle_total_due,
    car_total_due,
    pedal_cycle_total_due,
    parking_total_due,
    loss_of_earnings_due,
    childcare_total_due,
    misc_total_due,
    subsistence_due,
    smart_card_due,
    public_transport_total_paid,
    hired_vehicle_total_paid,
    motorcycle_total_paid,
    car_total_paid,
    pedal_cycle_total_paid,
    parking_total_paid,
    loss_of_earnings_paid,
    childcare_total_paid,
    misc_total_paid,
    subsistence_paid,
    smart_card_paid,
    total_travel_due,
    total_travel_paid,
    total_financial_loss_due,
    total_financial_loss_paid,
    total_subsistence_due,
    total_subsistence_paid,
    total_smart_card_due,
    total_smart_card_paid,
    total_travel_outstanding,
    total_financial_loss_outstanding,
    total_subsistence_outstanding,
    total_smartcard_outstanding,
    total_due,
    total_paid,
    total_outstanding,
    public_transport_total_approved + hired_vehicle_total_approved + motorcycle_total_approved + car_total_approved + pedal_cycle_total_approved + parking_total_approved + loss_of_earnings_approved + childcare_total_approved + misc_total_approved + subsistence_approved + smart_card_approved AS total_approved,
    public_transport_total_approved + hired_vehicle_total_approved + motorcycle_total_approved + car_total_approved + pedal_cycle_total_approved + parking_total_approved AS total_travel_approved,
    loss_of_earnings_approved + childcare_total_approved + misc_total_approved AS total_financial_loss_approved,
    subsistence_approved AS total_subsistence_approved,
    smart_card_approved AS total_smartcard_approved
   FROM ( SELECT llfad.public_transport_total_paid - COALESCE(lastapprovedllfad.public_transport_total_paid, 0::numeric) AS public_transport_total_approved,
            llfad.hired_vehicle_total_paid - COALESCE(lastapprovedllfad.hired_vehicle_total_paid, 0::numeric) AS hired_vehicle_total_approved,
            llfad.motorcycle_total_paid - COALESCE(lastapprovedllfad.motorcycle_total_paid, 0::numeric) AS motorcycle_total_approved,
            llfad.car_total_paid - COALESCE(lastapprovedllfad.car_total_paid, 0::numeric) AS car_total_approved,
            llfad.pedal_cycle_total_paid - COALESCE(lastapprovedllfad.pedal_cycle_total_paid, 0::numeric) AS pedal_cycle_total_approved,
            llfad.parking_total_paid - COALESCE(lastapprovedllfad.parking_total_paid, 0::numeric) AS parking_total_approved,
            llfad.loss_of_earnings_paid - COALESCE(lastapprovedllfad.loss_of_earnings_paid, 0::numeric) AS loss_of_earnings_approved,
            llfad.childcare_total_paid - COALESCE(lastapprovedllfad.childcare_total_paid, 0::numeric) AS childcare_total_approved,
            llfad.misc_total_paid - COALESCE(lastapprovedllfad.misc_total_paid, 0::numeric) AS misc_total_approved,
            llfad.subsistence_paid - COALESCE(lastapprovedllfad.subsistence_paid, 0::numeric) AS subsistence_approved,
                CASE
                    WHEN llfad.type::text = ANY (ARRAY['REAPPROVED_CASH'::character varying::text, 'REAPPROVED_BACS'::character varying::text]) THEN COALESCE(lastapprovedllfad.smart_card_paid, 0::numeric) - llfad.smart_card_paid
                    ELSE - (llfad.smart_card_paid - COALESCE(lastapprovedllfad.smart_card_paid, 0::numeric))
                END AS smart_card_approved,
            llfad.id,
            llfad.juror_revision,
            llfad.court_location_revision,
            llfad.type,
            llfad.created_by,
            llfad.created_on,
            llfad.juror_number,
            llfad.loc_code,
            llfad.created_on_date,
            llfad.last_approved_faudit,
            llfad.attendance_date,
            llfad.pool_number,
            llfad.trial_number,
            llfad.appearance_stage,
            llfad.attendance_type,
            llfad.is_draft_expense,
            llfad.pay_cash,
            llfad.f_audit,
            llfad.attendance_audit_number,
            llfad.public_transport_total_due,
            llfad.hired_vehicle_total_due,
            llfad.motorcycle_total_due,
            llfad.car_total_due,
            llfad.pedal_cycle_total_due,
            llfad.parking_total_due,
            llfad.loss_of_earnings_due,
            llfad.childcare_total_due,
            llfad.misc_total_due,
            llfad.subsistence_due,
            llfad.smart_card_due,
            llfad.public_transport_total_paid,
            llfad.hired_vehicle_total_paid,
            llfad.motorcycle_total_paid,
            llfad.car_total_paid,
            llfad.pedal_cycle_total_paid,
            llfad.parking_total_paid,
            llfad.loss_of_earnings_paid,
            llfad.childcare_total_paid,
            llfad.misc_total_paid,
            llfad.subsistence_paid,
            llfad.smart_card_paid,
            llfad.total_travel_due,
            llfad.total_travel_paid,
            llfad.total_financial_loss_due,
            llfad.total_financial_loss_paid,
            llfad.total_subsistence_due,
            llfad.total_subsistence_paid,
            llfad.total_smart_card_due,
            llfad.total_smart_card_paid,
            llfad.total_travel_outstanding,
            llfad.total_financial_loss_outstanding,
            llfad.total_subsistence_outstanding,
            llfad.total_smartcard_outstanding,
            llfad.total_due,
            llfad.total_paid,
            llfad.total_outstanding
           FROM juror_mod.low_level_financial_audit_details llfad
             LEFT JOIN juror_mod.low_level_financial_audit_details lastapprovedllfad ON lastapprovedllfad.id = llfad.last_approved_faudit AND lastapprovedllfad.loc_code::text = llfad.loc_code::text AND lastapprovedllfad.attendance_date = llfad.attendance_date AND (llfad.type::text = ANY (ARRAY['REAPPROVED_BACS'::character varying::text, 'REAPPROVED_CASH'::character varying::text]))) llfad2;


-- juror_mod.failed_to_attend source

CREATE OR REPLACE VIEW juror_mod.failed_to_attend
AS SELECT jp.owner,
    jp.pool_number,
    j.juror_number,
    j.first_name,
    j.last_name,
    j.postcode,
    js.status_desc,
    j.date_disq,
    jh.date_created AS date_printed,
    jp.is_active,
    a.attendance_date,
    row_number() OVER (PARTITION BY j.juror_number ORDER BY j.date_disq DESC) AS row_no
   FROM juror_mod.juror_pool jp
     JOIN juror_mod.juror j ON j.juror_number::text = jp.juror_number::text
     JOIN juror_mod.t_juror_status js ON js.status = jp.status
     JOIN juror_mod.appearance a ON a.juror_number::text = jp.juror_number::text
     LEFT JOIN juror_mod.juror_history jh ON jh.juror_number::text = jp.juror_number::text AND jh.pool_number::text = jp.pool_number::text AND jh.history_code::text = 'RFTA'::text
  WHERE a.no_show = true AND a.attendance_type::text = 'ABSENT'::text AND jp.owner::text <> '400'::text;


-- juror_mod.show_cause source

CREATE OR REPLACE VIEW juror_mod.show_cause
AS SELECT jp.owner,
    jp.pool_number,
    j.juror_number,
    j.first_name,
    j.last_name,
    j.postcode,
    js.status_desc,
    j.date_disq,
    jh.date_created AS date_printed,
    jp.is_active,
    a.attendance_date,
    row_number() OVER (PARTITION BY j.juror_number ORDER BY j.date_disq DESC) AS row_no
   FROM juror_mod.juror_pool jp
     JOIN juror_mod.juror j ON j.juror_number::text = jp.juror_number::text
     JOIN juror_mod.t_juror_status js ON js.status = jp.status
     JOIN juror_mod.appearance a ON a.juror_number::text = jp.juror_number::text
     LEFT JOIN juror_mod.juror_history jh ON jh.juror_number::text = jp.juror_number::text AND jh.pool_number::text = jp.pool_number::text AND jh.history_code::text = 'RSHC'::text
  WHERE a.no_show = true AND a.attendance_type::text = 'ABSENT'::text AND jp.owner::text <> '400'::text;
